Repository playframework/play-soap, pull requests merged in 2020-10, with the labels that each got.

#209 Update sbt to 1.4.0
  project/build.properties
Labels: dependencies

#205 Remove `status:merge-when-green` after merge
  .mergify.yml
Labels: maintenance, status:merge-when-green

#210 Update scalafmt-core to 2.7.4
  .scalafmt.conf
Labels: dependencies, status:merge-when-green

#211 Update specs2-core to 4.10.4
  project/Dependencies.scala
Labels: dependencies

#212 Update specs2-core to 4.10.5
  project/Dependencies.scala
Labels: dependencies

#213 Update scalafmt-core to 2.7.5
  .scalafmt.conf
Labels: dependencies, status:merge-when-green

#214 Update sbt to 1.4.1
  project/build.properties
Labels: dependencies, status:merge-when-green

#216 Fix the link to community driven definition
  README.md
Labels: maintenance, status:merge-when-green

#217 Update sbt-bintray to 0.6.0
  project/plugins.sbt
Labels: dependencies, status:merge-when-green

#219 Update play, play-specs2, sbt-plugin to 2.7.6
  project/Dependencies.scala
Labels: dependencies, status:merge-when-green
