Repository playframework/play-soap, pull requests merged in 2020-05, with the labels that each got.

#145 #144 SOAP1.2 support
  client/src/main/scala/play/soap/PlaySoapPlugin.scala
Labels: block-merge

#178 Categorize of drafter template
  .github/release-drafter.yml
Labels: maintenance

#181 Fix Bintray package name for sbt plugin
  project/Publish.scala
Labels: maintenance

#182 Labeling for Scala Steward PR's
  .mergify.yml
Labels: maintenance

#179 Update scalafmt-core to 2.5.3
  .scalafmt.conf
Labels: dependencies

#183 Fix publishing documentation
  .travis.yml
  scripts/publish
Labels: maintenance
