Repository playframework/play-soap, pull requests merged in 2022-11, with the labels that each got.

#347 sbt 1.8.0-RC1
  plugin/src/sbt-test/play-soap/incremental-compilation/project/plugins.sbt
  plugin/src/sbt-test/play-soap/multiple-ports/project/plugins.sbt
  plugin/src/sbt-test/play-soap/simple-client-play-java-future/project/plugins.sbt
  plugin/src/sbt-test/play-soap/simple-client-scala-future/project/plugins.sbt
  project/build.properties
Labels: maintenance, status:merge-when-green

#328 🔄 Synced file(s) with playframework/.github
  build.sbt
  common.sbt
Labels: maintenance, sync

#348 🔄 Synced `common.sbt` with playframework/.github
  common.sbt
Labels: maintenance, sync

#350 sbt-java-formatter 0.8.0 (was 0.7.0)
  .git-blame-ignore-revs
  client/src/test/java/play/soap/mockservice/MockServiceScala.java
  plugin/src/main/java/play/soap/plugin/PlayClientGenerator.java
  project/plugins.sbt
Labels: type:updates

#352 sbt 1.8.0 (was 1.8.0-RC1)
  project/build.properties
Labels: type:updates

#355 specs2-core 4.19.0 (was 4.17.0)
  project/Dependencies.scala
Labels: type:updates

#351 sbt-header 5.9.0 (was 5.7.0)
  project/plugins.sbt
Labels: type:updates

#354 scalafmt-core 3.6.1 (was 3.6.0)
  .scalafmt.conf
Labels: type:updates

#353 sbt-scalafmt 2.5.0 (was 2.4.6)
  project/plugins.sbt
Labels: status:merge-when-green, type:updates
