Repository playframework/play-soap, pull requests merged in 2023-02, with the labels that each got.

#360 Upgrade CXF to 4.X
  client/src/main/scala/play/soap/PlayJaxWsClientProxy.scala
  client/src/main/scala/play/soap/PlayJaxWsProxyFactoryBean.scala
  client/src/main/scala/play/soap/PlaySoapPlugin.scala
  client/src/test/java/play/soap/mockservice/MockService.java
  client/src/test/java/play/soap/mockservice/MockServiceImpl.java
  client/src/test/java/play/soap/mockservice/MockServiceJava.java
  client/src/test/java/play/soap/mockservice/MockServiceScala.java
  client/src/test/scala/play/soap/PlayJaxWsClientProxySpec.scala
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/highlights.adoc
  project/Dependencies.scala
Labels: enhancement, type:updates

#363 Readme cleaning
  README.md
  docs/modules/ROOT/pages/index.adoc
Labels: maintenance

#364 Fix imports in service template (CXF 4)
  plugin/src/main/resources/play/soap/plugin/client.vm
Labels: bug

#362 Integration tests for primitive types
  build.sbt
  project/Common.scala
  project/Dependencies.scala
  project/plugins.sbt
  test/java/src/test/java/play/soap/test/PrimitivesTest.java
  test/scala/src/test/scala/play/soap/test/PrimitivesSpec.scala
  test/server/src/main/java/play/soap/test/primitives/PrimitivesImpl.java
  test/server/src/main/resources/wsdl/helloworld.wsdl
  test/server/src/main/resources/wsdl/primitives.wsdl
Labels: maintenance

#369 scalafmt-core 3.7.1 (was 3.6.1)
  .scalafmt.conf
Labels: type:updates

#367 sbt-native-packager 1.9.15 (was 1.9.13)
  project/plugins.sbt
Labels: type:updates
