Repository playframework/play-soap, pull requests merged in 2025-06, with the labels that each got.

#478 Patch updates
  .git-blame-ignore-revs
  .scalafmt.conf
  build.sbt
  client/src/main/scala/play/soap/PlayJaxWsClientProxy.scala
  client/src/main/scala/play/soap/PlaySoapPlugin.scala
  plugin/src/sbt-test/play-soap/simple-client-scala-future/tests/play/soap/sbtplugin/tester/HelloWorldSpec.scala
  project/Common.scala
  project/Dependencies.scala
Labels: type:updates

#480 Move to `org.playframework` group id
  README.md
  docs/modules/ROOT/pages/plugin/gradle.adoc
  docs/modules/ROOT/pages/plugin/maven.adoc
  docs/modules/ROOT/pages/plugin/sbt.adoc
  plugin/src/sbt-test/play-soap/incremental-compilation/build.sbt
  plugin/src/sbt-test/play-soap/incremental-compilation/project/plugins.sbt
  plugin/src/sbt-test/play-soap/multiple-ports/build.sbt
  plugin/src/sbt-test/play-soap/multiple-ports/project/plugins.sbt
  plugin/src/sbt-test/play-soap/simple-client-play-java-future/project/plugins.sbt
  plugin/src/sbt-test/play-soap/simple-client-scala-future/project/plugins.sbt
  project/Common.scala
Labels: maintenance

#482 sbt, scripted-plugin 1.11.1 (was 1.10.11)
  project/build.properties
Labels: type:updates

#481 sbt-ci-release 1.11.1 (was 1.9.3)
  project/plugins.sbt
Labels: type:updates

#483 Support for Play 3
  client/src/main/scala/play/soap/PlayJaxWsClientProxy.scala
  client/src/test/scala/play/soap/PlayJaxWsClientProxySpec.scala
  project/Dependencies.scala
Labels: dependencies

#485 Support for Scala 3
  build.sbt
  client/src/main/scala/play/soap/PlayJaxWsProxyFactoryBean.scala
  client/src/main/scala/play/soap/PlaySoapPlugin.scala
  project/Common.scala
  project/Dependencies.scala
  test/scala/src/test/scala/play/soap/test/PrimitivesSpec.scala
Labels: enhancement

#487 Patch updates
  project/Dependencies.scala
Labels: type:updates
